# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Launch International
tagline:          'The Journey Of Innovation.'
description:      'Our primary goal is to support businesses and help them reach their full potential. Launch is a digital platform for accelerating business, driving innovation and turbo-charging productivity at the touch of a button'
description2:     'Launch seeks to utilise the latest developments in open data, big data analysis, and intelligent information matching systems, in order to assist our partners in identifying funding sources for their innovation projects.'
keywords:         'Launch, Launch International, Innovation, Funding, big data, information matching, business'
url:              
baseurl:          

# Social
twitter:          launch_int

# Contact
email:            contact@launchinternational.co.uk

author:
  name:           'Knownow Information'
  url:            https://kn-i.com

# paginate:         2
# paginate_path:      'blog/page:num'

gist:
noscript:         false

# Gems
gems:             [jekyll-paginate]

github:           
  repo:           mrsideshowjack/launch-static
repository:       mrsideshowjack/launch-static
